import type { Facets } from './mandi/types';
import catalogJson from '../data/catalog.json';

/**
 * The generated catalog: every state, district, market and commodity that has appeared
 * in the dataset, with a stable URL slug for each and the exact upstream value to filter
 * by.
 *
 * This exists because the upstream API has no aggregation endpoint - "which commodities
 * are traded in Andhra Pradesh?" cannot be answered at request time at any price. The
 * catalog is generated by `scripts/build-catalog.ts` and drives dropdowns, search,
 * `generateStaticParams`, sitemaps and slug -> filter-value resolution.
 */

export interface CatalogEntry {
  slug: string;
  /** Exact upstream value. Must be passed verbatim to a `.keyword` filter. */
  api: string;
  name: string;
}

export interface CatalogMarket extends CatalogEntry {
  districtSlug: string;
}

export interface CatalogDistrict extends CatalogEntry {
  markets: CatalogMarket[];
}

export interface CatalogState extends CatalogEntry {
  districts: CatalogDistrict[];
  /** Commodity slugs seen in this state. */
  commoditySlugs: string[];
  /** Records seen for this state when the catalog was built - used to rank pages. */
  recordCount: number;
}

export interface Catalog {
  generatedAt: string;
  sourceUpdatedAt: string | null;
  states: CatalogState[];
  commodities: (CatalogEntry & { recordCount: number })[];
}

const catalog = catalogJson as unknown as Catalog;

interface CatalogIndex {
  catalog: Catalog;
  facets: Facets;
  stateBySlug: Map<string, CatalogState>;
  commodityBySlug: Map<string, CatalogEntry & { recordCount: number }>;
  /** Keyed `${stateSlug}/${districtSlug}`. */
  districtBySlug: Map<string, CatalogDistrict & { stateSlug: string }>;
  /** Keyed `${stateSlug}/${marketSlug}`. */
  marketBySlug: Map<string, CatalogMarket & { stateSlug: string }>;
}

let indexed: CatalogIndex | null = null;

function buildIndex(): CatalogIndex {
  const stateBySlug = new Map<string, CatalogState>();
  const districtBySlug = new Map<string, CatalogDistrict & { stateSlug: string }>();
  const marketBySlug = new Map<string, CatalogMarket & { stateSlug: string }>();
  const commodityBySlug = new Map<string, CatalogEntry & { recordCount: number }>();

  const districtsByState: Record<string, string[]> = {};
  const marketsByState: Record<string, string[]> = {};
  const commoditiesByState: Record<string, string[]> = {};

  for (const c of catalog.commodities) commodityBySlug.set(c.slug, c);

  for (const state of catalog.states) {
    stateBySlug.set(state.slug, state);
    districtsByState[state.api] = [];
    marketsByState[state.api] = [];
    commoditiesByState[state.api] = state.commoditySlugs
      .map((s) => commodityBySlug.get(s)?.api)
      .filter((v): v is string => Boolean(v));

    for (const district of state.districts) {
      districtBySlug.set(`${state.slug}/${district.slug}`, { ...district, stateSlug: state.slug });
      districtsByState[state.api].push(district.api);
      for (const market of district.markets) {
        marketBySlug.set(`${state.slug}/${market.slug}`, { ...market, stateSlug: state.slug });
        marketsByState[state.api].push(market.api);
      }
    }
  }

  return {
    catalog,
    stateBySlug,
    districtBySlug,
    marketBySlug,
    commodityBySlug,
    facets: {
      states: catalog.states.map((s) => s.api),
      districtsByState,
      marketsByState,
      commoditiesByState,
      commodities: catalog.commodities.map((c) => c.api),
    },
  };
}

function getIndex(): CatalogIndex {
  indexed ??= buildIndex();
  return indexed;
}

export async function loadCatalog(): Promise<CatalogIndex> {
  return getIndex();
}

export function getStates(): CatalogState[] {
  return getIndex().catalog.states;
}

export function getCommodities() {
  return getIndex().catalog.commodities;
}

export function findState(slug: string): CatalogState | undefined {
  return getIndex().stateBySlug.get(slug);
}

export function findCommodity(slug: string) {
  return getIndex().commodityBySlug.get(slug);
}

export function findDistrict(stateSlug: string, districtSlug: string) {
  return getIndex().districtBySlug.get(`${stateSlug}/${districtSlug}`);
}

export function findMarket(stateSlug: string, marketSlug: string) {
  return getIndex().marketBySlug.get(`${stateSlug}/${marketSlug}`);
}

/** Commodities known to trade in a state, richest first. */
export function commoditiesInState(state: CatalogState) {
  const idx = getIndex();
  return state.commoditySlugs
    .map((s) => idx.commodityBySlug.get(s))
    .filter((c): c is CatalogEntry & { recordCount: number } => Boolean(c))
    .sort((a, b) => b.recordCount - a.recordCount);
}

export function catalogMeta() {
  const { catalog: c } = getIndex();
  return { generatedAt: c.generatedAt, sourceUpdatedAt: c.sourceUpdatedAt };
}
